// The 4690 (1309 GSA level) action code sheet as published on the original
// reference pages, kept verbatim so a technician can look up any code an operator
// remembers from a legacy lane and see what SureFlow does with it today.
//
// This list is REFERENCE ONLY — the live behaviour comes from the ActionCode
// entity. The admin reference table joins the two on the code number.

export const SHEET_GROUPS = [
  {
    id: "core",
    label: "Core Register Functions",
    note: "The everyday codes. Most of these are mapped in SureFlow.",
    codes: [
      { code: 0, name: "AC_SAMS_LOAN_PROCESS" },
      { code: 1, name: "AC_VOID_PREVIOUS_TRANS" },
      { code: 2, name: "AC_TERMINAL_STATS_REPORT" },
      { code: 3, name: "AC_TERMINAL_ACCOUNT_REPORT" },
      { code: 4, name: "AC_DEPARTMENT_TOTALS" },
      { code: 5, name: "AC_ITEM_MOVEMENT" },
      { code: 6, name: "AC_PRICE_INQUIRY" },
      { code: 7, name: "AC_RESET_TRANSACTION_NUM" },
      { code: 8, name: "AC_REGISTER_REENTRY_MODE" },
      { code: 9, name: "AC_REGISTER_TRAINING_MODE" },
      { code: 10, name: "AC_PRINT_OPERATOR_STATS" },
      { code: 11, name: "AC_SAMS_VOID_PREVIOUS_TRANS" },
      { code: 12, name: "AC_PKG_ACTION_CODE" },
      { code: 13, name: "AC_CHECK_CASHING" },
      { code: 14, name: "AC_MEMORY_USAGE" },
      { code: 15, name: "AC_WIC_ICC_BALANCE" },
      { code: 16, name: "AC_PRINT_LAYAWAY_EVENTS" },
      { code: 17, name: "AC_TAX_TABLE_REFRESH" },
      { code: 18, name: "AC_CONFIG_PARMS_REFRESH" },
      { code: 19, name: "AC_RELOAD_PROMPTS" },
      { code: 20, name: "AC_TWENTY" },
      { code: 21, name: "AC_PROCESS_VAT_INVOICE" },
      { code: 22, name: "AC_OVER_SHORT_REPORT" },
      { code: 23, name: "AC_SUSPEND_REPORT" },
      { code: 24, name: "AC_SUPERVISOR_OVERRIDE" },
      { code: 25, name: "AC_GIFT_CARD_CASH_BACK" },
      { code: 26, name: "AC_CURR_EXCHANGE" },
      { code: 27, name: "AC_TAX_REFUND" },
      { code: 28, name: "AC_FAPIO_INVOICE_NUMBER" },
      { code: 29, name: "AC_HOME_DELIVERY" },
      { code: 30, name: "AC_PAYCHECK_PROCESS" },
      { code: 31, name: "AC_CHECK_EXCHANGE_PROCESS" },
      { code: 32, name: "AC_TOGGLE_TENANT_SALES" },
      { code: 33, name: "AC_PRINT_TENANT_LIST" },
      { code: 34, name: "AC_LOAN_PROCESS" },
    ],
  },
  {
    id: "fiscal",
    label: "Fiscal Printer & Electronic Journal",
    note: "Non-US fiscal memory devices. Not applicable to SureFlow.",
    codes: [
      { code: 35, name: "AC_DUMP_FISCAL_EJ" },
      { code: 36, name: "AC_DUMP_FISCAL_MEMORY" },
      { code: 37, name: "AC_SAMS_INIT_FISCAL_CONFIG" },
      { code: 38, name: "AC_SAMS_REPRINT_FISCAL_SALE" },
      { code: 39, name: "AC_SAMS_REPRINT_FISCAL_RETURN" },
      { code: 41, name: "AC_OPEN_FISCAL_PROCESS" },
      { code: 42, name: "AC_CLOSE_FISCAL_PROCESS" },
      { code: 43, name: "AC_MONTHLY_FISCAL_PROCESS" },
      { code: 44, name: "AC_PRINT_ZREADINGS_COMPLETED" },
      { code: 45, name: "AC_PRINT_INVOICE_SUMMARY" },
      { code: 49, name: "AC_INIT_FISCAL_CONFIG" },
    ],
  },
  {
    id: "store_ops",
    label: "Store Operations & Receipts",
    note: "Salesman mode, journal chits, receipt reprints and logo reloads.",
    codes: [
      { code: 39, name: "AC_SELECT_SNACK_MENU" },
      { code: 40, name: "AC_SET_SALESMAN_MODE" },
      { code: 46, name: "AC_RELOAD_LOGO_AND_GRAPHICS" },
      { code: 47, name: "AC_PARKING_LOT_PAYMENT" },
      { code: 50, name: "AC_CLIENT_DATA" },
      { code: 51, name: "AC_PRINT_PERSONALIZED_RCPT" },
      { code: 52, name: "AC_PERSONALIZED_RCPT_SUMMARY" },
      { code: 55, name: "AC_RELOAD_PHONE_CARD" },
      { code: 56, name: "AC_SERVICE_PAYMENT" },
      { code: 60, name: "AC_PRINT_JOURNAL_CHIT" },
      { code: 61, name: "AC_PRINT_PREV_RECEIPT" },
      { code: 65, name: "AC_SET_MONEY_ORDER_PRINTER" },
      { code: 66, name: "AC_SET_MONEY_ORDER_REGISTER" },
      { code: 69, name: "AC_ON_LINE_TRAINING_DOCS" },
      { code: 70, name: "AC_UTILITY_PAYMENT" },
      { code: 73, name: "AC_MONEY_ORDER_LOG" },
      { code: 74, name: "AC_VENDOR_PAYMENT" },
      { code: 75, name: "AC_NO_FEE_MONEY_ORDER" },
      { code: 76, name: "AC_ENTER_COIN_VOUCHER" },
      { code: 78, name: "AC_CAT_MGMT_MENU" },
      { code: 80, name: "AC_FUEL_REPRINT_RECEIPT" },
      { code: 81, name: "AC_FUEL_TEST" },
      { code: 84, name: "AC_PRINT_ENABLECODE128_BARCODE" },
      { code: 85, name: "AC_TESTCODE128FORHANDHELD" },
      { code: 91, name: "AC_TC_REFUND_HISTORY" },
      { code: 93, name: "AC_PRINT_MSR_TRACK_DATA" },
      { code: 94, name: "AC_PRINT_TEST_BARCODES" },
      { code: 95, name: "AC_TERMINAL_MGMT" },
      { code: 98, name: "AC_ENABLE_TRACING" },
      { code: 99, name: "AC_PRINT_HELP_MSGS" },
    ],
  },
  {
    id: "money_services",
    label: "MoneyGram, Bill Pay & PIP",
    note: "Third-party money transfer and photo services. Not offered by SureFlow.",
    codes: [
      { code: 100, name: "AC_PAF_MENU" },
      { code: 101, name: "AC_MONEY_GRAM_SEND" },
      { code: 102, name: "AC_MONEY_GRAM_RECEIVE" },
      { code: 103, name: "AC_MONEY_GRAM_EXPRESS_PAY" },
      { code: 104, name: "AC_MONEY_GRAM_SERVICE_ACTIVITY" },
      { code: 105, name: "AC_MONEY_GRAM_AMEND_TRANS" },
      { code: 106, name: "AC_MONEY_GRAM_AGENT_DIRECTORY" },
      { code: 107, name: "AC_MONEY_GRAM_BILLER_DIRECTORY" },
      { code: 108, name: "AC_MONEY_GRAM_FEE_QUOTE" },
      { code: 110, name: "AC_CARWASH_REGISTER_SALE" },
      { code: 111, name: "AC_BILL_PAY_PAYMENT" },
      { code: 112, name: "AC_BILL_PAY_SEARCH" },
      { code: 113, name: "AC_PRINT_OFFERED_SAVINGS" },
      { code: 114, name: "AC_WMDOTCOM_ORDER_NUM_SEARCH" },
      { code: 115, name: "AC_WMDOTCOM_TC_NUM_SEARCH" },
      { code: 116, name: "AC_WMDOTCOM_UPC_EMAIL_SEARCH" },
      { code: 117, name: "AC_TOGGLE_SHOP_BAG" },
      { code: 120, name: "AC_PRINT_SUPR_ID_BARCODE" },
      { code: 121, name: "AC_PIP_ORDER_LOOKUP" },
      { code: 122, name: "AC_PIP_SEARCH_BY_EMAIL" },
      { code: 123, name: "AC_PIP_SEARCH_BY_PHONE" },
      { code: 124, name: "AC_PIP_SEARCH_BY_NAME" },
      { code: 125, name: "AC_PIP_ORDER_REVERSAL" },
      { code: 126, name: "AC_ONE_HOUR_GUARANTEE" },
      { code: 127, name: "AC_TIRE_LUBE_EXPRESS" },
    ],
  },
  {
    id: "till",
    label: "Till Handling",
    note: "Swapping, counting and lifting cash out of a lane's till.",
    codes: [
      { code: 150, name: "AC_TILL_SWAP_OUT" },
      { code: 151, name: "AC_TILL_CHANGE_RUN" },
      { code: 152, name: "AC_TILL_RESET" },
      { code: 153, name: "AC_TILL_CASH_LIFT" },
      { code: 154, name: "AC_GET_TILL_COUNT" },
      { code: 159, name: "AC_TILL_CALIBRATE" },
      { code: 189, name: "AC_REFRESH_DEBIT_NOW" },
      { code: 190, name: "AC_INJECT_TEMP_TLOG" },
    ],
  },
  {
    id: "discounts",
    label: "Percentage Discounts & Lookups",
    note: "One-touch markdowns and receipt history lookups.",
    codes: [
      { code: 300, name: "AC_ANY_PERCENT_OFF" },
      { code: 301, name: "AC_10_PERCENT_OFF" },
      { code: 302, name: "AC_20_PERCENT_OFF" },
      { code: 303, name: "AC_30_PERCENT_OFF" },
      { code: 304, name: "AC_40_PERCENT_OFF" },
      { code: 305, name: "AC_50_PERCENT_OFF" },
      { code: 330, name: "AC_RECEIPT_HISTORY_LOOKUP" },
      { code: 333, name: "AC_MOBILE_TRANSACTION_LOOKUP" },
      { code: 350, name: "AC_WM_S2S" },
      { code: 351, name: "AC_SIGUI_LAYAWAY" },
    ],
  },
  {
    id: "csm",
    label: "CSM Assistance & Status Calls",
    note: "The operator pages the CSM with a specific need instead of a generic call.",
    codes: [
      { code: 200, name: "AC_CSM_WS_ACTIVATE" },
      { code: 201, name: "AC_CSM_201" },
      { code: 202, name: "AC_CSM_CANCEL_PREVIOUS" },
      { code: 203, name: "AC_CSM_NEED_CHANGE" },
      { code: 204, name: "AC_CSM_NEED_RESTROOM" },
      { code: 205, name: "AC_CSM_NEED_BREAK" },
      { code: 206, name: "AC_CSM_NEED_RECEIPTTAPE" },
      { code: 207, name: "AC_CSM_NEED_CARRYOUT" },
      { code: 208, name: "AC_CSM_NEED_CASHPICKUP" },
      { code: 209, name: "AC_CSM_NEED_PRICECHECK" },
      { code: 210, name: "AC_CSM_NEED_CLEANUP" },
      { code: 211, name: "AC_CSM_NEED_BREAK100" },
      { code: 212, name: "AC_CSM_NEED_LOAN" },
      { code: 213, name: "AC_CSM_WIC" },
      { code: 214, name: "AC_CSM_LONG_LINES" },
      { code: 215, name: "AC_CSM_NEED_CLEANUP_WET" },
      { code: 216, name: "AC_CSM_EMERGENCY" },
      { code: 217, name: "AC_CSM_NEED_ROUND_OF_CHANGE" },
      { code: 218, name: "AC_CSM_NEED_CHECK_APPROVAL" },
      { code: 219, name: "AC_CSM_NEED_BAGS" },
      { code: 220, name: "AC_CSM_NEED_STAMPS" },
      { code: 221, name: "AC_CSM_NEED_PROPANE" },
      { code: 222, name: "AC_CSM_NEED_MO_PAPER" },
      { code: 223, name: "AC_CSM_MO_PRINTER_ERROR" },
      { code: 224, name: "AC_CSM_CHECK_OUTPUT_TRAY" },
      { code: 225, name: "AC_CSM_OUTPUT_TRAY_CLEARED" },
      { code: 226, name: "AC_CSM_CUST_NEED_ASSIST" },
      { code: 227, name: "AC_CSM_CONCORD_COMM_LINK_DOWN" },
      { code: 228, name: "AC_CSM_CONCORD_COMM_LINK_UP" },
      { code: 229, name: "AC_CSM_GATEWAY_COMM_LINK_DOWN" },
      { code: 230, name: "AC_CSM_GENIRIC_ERROR_MSG" },
      { code: 231, name: "AC_CSM_100_CURRENCY_LOW" },
      { code: 232, name: "AC_CSM_20_CURRENCY_LOW" },
      { code: 233, name: "AC_CSM_5_CURRENCY_LOW" },
      { code: 234, name: "AC_CSM_1_CURRENCY_LOW" },
      { code: 235, name: "AC_CSM_100_CURRENCY_OUT" },
      { code: 236, name: "AC_CSM_20_CURRENCY_OUT" },
      { code: 237, name: "AC_CSM_5_CURRENCY_OUT" },
      { code: 238, name: "AC_CSM_1_CURRENCY_OUT" },
      { code: 239, name: "AC_CSM_COIN_CURRENCY_LOW" },
      { code: 240, name: "AC_CSM_COIN_CURRENCY_OUT" },
      { code: 241, name: "AC_CSM_CATASTROPHIC_FAILURE" },
      { code: 242, name: "AC_CSM_CASH_ACCEPTOR_JAMMED" },
      { code: 243, name: "AC_CSM_CASH_DISPENSER_JAMMED" },
      { code: 244, name: "AC_CSM_CHECK_READER_JAMMED" },
      { code: 245, name: "AC_CSM_RECEIPT_PRINTER_JAMMED" },
      { code: 246, name: "AC_CSM_URGENT_FINCEN_EXCEEDED" },
      { code: 247, name: "AC_CSM_BACK_CHECK_PRINTING_ERROR" },
      { code: 248, name: "AC_CSM_NEED_ASSISTANCE" },
      { code: 249, name: "AC_CSM_END_REQUESTS" },
      { code: 250, name: "AC_CSM_NOSALE" },
      { code: 251, name: "AC_CSM_ABORT" },
      { code: 252, name: "AC_CSM_SUSPEND" },
      { code: 253, name: "AC_CSM_DISC" },
      { code: 254, name: "AC_CSM_LWY_FEES" },
      { code: 255, name: "AC_CSM_SAMS_MEMB_REG" },
      { code: 256, name: "AC_CSM_SAMS_RFND_REG" },
      { code: 257, name: "AC_CSM_SAMS_SPC_MBR_REG" },
      { code: 258, name: "AC_CSM_SAMS_CAFE_REG" },
      { code: 259, name: "AC_CSM_SAMS_TEMPMBRNBR" },
      { code: 260, name: "AC_CSM_BALANCEO" },
      { code: 261, name: "AC_CSM_CCTA_FORM" },
      { code: 263, name: "AC_CSM_FAILED_AGE_RESTRICT" },
      { code: 264, name: "AC_CSM_SAMS_PLUS_UPGRADE" },
      { code: 265, name: "AC_CSM_SSCO_TO_FRONT_REG" },
      { code: 266, name: "AC_CSM_FRONT_TO_SSCO_REG" },
      { code: 267, name: "AC_CSM_REMOVE_UNPROCESSED_CHECK" },
      { code: 268, name: "AC_CSM_CRITICAL_ERROR_FIELD_SUPPORT" },
      { code: 270, name: "AC_ALCOHOL_AGE_TO_SELL" },
    ],
  },
  {
    id: "devices",
    label: "Device Control & Terminal Config",
    note: "Enabling scales and peripherals, terminal configuration and wake/boot.",
    codes: [
      { code: 400, name: "AC_DEVCTL_ENABLE" },
      { code: 401, name: "AC_DEVCTL_DISABLE" },
      { code: 402, name: "AC_DEVCTL_LEVEL" },
      { code: 403, name: "AC_DEVCTL_PED_ACTIVATE" },
      { code: 410, name: "AC_SCALE_ENABLE" },
      { code: 411, name: "AC_SCALE_DISABLE" },
      { code: 500, name: "AC_CONFIGURE_GUI_PROMOTIONS" },
      { code: 501, name: "AC_REMOTE_DISK_BOOT" },
      { code: 502, name: "AC_TERMINAL_CONFIG" },
      { code: 503, name: "AC_TERM_CONFIG_STATUS" },
      { code: 504, name: "AC_WAKE_TERM" },
      { code: 666, name: "AC_DUMP_REGISTER" },
    ],
  },
  {
    id: "atm",
    label: "ATM Plus",
    note: "In-lane ATM withdrawals and balance enquiries. Not offered by SureFlow.",
    codes: [
      { code: 770, name: "AC_ATM_PLUS_INIT" },
      { code: 771, name: "AC_ATM_PLUS_CHECK_WITHDRWL" },
      { code: 772, name: "AC_ATM_PLUS_SAVING_WITHDRWL" },
      { code: 773, name: "AC_ATM_PLUS_CREDIT_WITHDRWL" },
      { code: 774, name: "AC_ATM_PLUS_CHECK_BALANCE" },
      { code: 775, name: "AC_ATM_PLUS_SAVING_BALANCE" },
      { code: 776, name: "AC_ATM_PLUS_CREDIT_BALANCE" },
      { code: 777, name: "AC_ATM_PLUS_CHECK_TO_SAVING" },
      { code: 778, name: "AC_ATM_PLUS_SAVING_TO_CHECK" },
      { code: 779, name: "AC_ATM_PLUS_EOD_RESET" },
    ],
  },
  {
    id: "transfer",
    label: "Verification & Transaction Transfer",
    note: "Age checks, mobile checkout and moving a live sale between lanes.",
    codes: [
      { code: 801, name: "AC_AGE_VERIFICATION" },
      { code: 802, name: "AC_MCX_CANCEL" },
      { code: 803, name: "AC_MCX_PRINTQR" },
      { code: 804, name: "AC_MCX_TOGGLE_QR_PINPAD" },
      { code: 850, name: "AC_INITIATE_TRANS_TRANSFER" },
      { code: 851, name: "AC_RETRIEVE_TRANS_TRANSFER" },
      { code: 855, name: "AC_PROCESS_CASHCHGR_FUNCTION" },
      { code: 888, name: "AC_TOUCH_DISPLAY_SWAP" },
    ],
  },
  {
    id: "diagnostics",
    label: "Diagnostics & Certification",
    note: "Technician print tests, memory checks and configuration APIs.",
    codes: [
      { code: 901, name: "AC_PRINT_TEST_SLIP" },
      { code: 902, name: "AC_TEST_VIDEO_COLOR" },
      { code: 903, name: "AC_TEST_MEMORY_LEAK" },
      { code: 904, name: "AC_PRINT_ALL_PROMPTS" },
      { code: 905, name: "AC_PRINT_ALL_MESSAGES" },
      { code: 906, name: "AC_MEMORY_ALLOCATION" },
      { code: 907, name: "AC_CAPTURE_SIGNATURES" },
      { code: 908, name: "AC_TEST_CASH_EXCHANGE" },
      { code: 909, name: "AC_DIR_RAM_DRIVE" },
      { code: 910, name: "AC_CHAIN_APPLICATION" },
      { code: 911, name: "AC_PRINT_ITEM_TIMES" },
      { code: 950, name: "AC_GOV_CERTIFICATION" },
      { code: 960, name: "AC_TEST_CONFIG_API" },
    ],
  },
];