// Physical keyboard layout model for the visual remapper.
//
// Three layers, kept deliberately separate:
//   scancode  — what the hardware sends (captured once per model with evtest)
//   keycode   — what hwdb remaps it to, and what the browser delivers as e.code
//   function  — which FunctionKey.key_number the POS runs for that keycode
//
// The remapper only ever changes the third layer plus the keycode assignment;
// scancodes belong to the hardware and are captured, never invented.

export const DEFAULT_KEYBOARD_MODEL = "IBM 3AA01194300";

// The 4x4 function-key block as it ships on the lane keyboards. Cap labels mirror
// the physical keycaps so a technician can match the screen to the hardware.
// Scancodes start blank — the model must be calibrated before the map is real.
const CAPS = [
  ["VENDOR COUPON", "QTY", "PS MERC RETURN", "ITEM INQUIRY"],
  ["STORE PAY", "SHOP CARD", "PRICE OVERRIDE", "ITEM INQUIRY 2"],
  ["CHECK", "CREDIT DEBIT EBT", "TRANS DISC", "VOID"],
  ["CASH", "TOTAL", "ACTION CODE", "ABORT TRANS."],
];

// F9 (Action Code) and F10 (Ctrl+Action Code, silent robbery alarm) are reserved.
// The POS depends on both, so their slots are locked in the editor.
export const RESERVED_KEYCODES = ["f9", "f10"];

export const KEYCODE_OPTIONS = [...Array.from({ length: 16 }, (_, i) => `f${i + 1}`), "backspace", "enter"];

// The blank keycap directly under CTRL on the numeric pad. Mapped to backspace so
// it deletes the last digit on every POS pinpad.
const NUMPAD_CLEAR_CAP = "CLEAR (UNDER CTRL)";

// The double-height cap below CLEAR — the pad's ENTER key, used to submit pinpads.
const NUMPAD_ENTER_CAP = "ENTER (DOUBLE KEY)";

export function buildDefaultSlots() {
  const slots = [];
  CAPS.forEach((row, r) => {
    row.forEach((cap, c) => {
      const isActionCode = cap === "ACTION CODE";
      slots.push({
        slot_id: `r${r + 1}c${c + 1}`,
        row: r + 1,
        col: c + 1,
        cap_label: cap,
        scancode: isActionCode ? "70045" : "",
        keycode: isActionCode ? "f9" : "",
        function_key_number: null,
        locked: isActionCode,
      });
    });
  });
  slots.push({
    slot_id: "np1",
    row: 5,
    col: 1,
    cap_label: NUMPAD_CLEAR_CAP,
    scancode: "",
    keycode: "backspace",
    function_key_number: null,
    locked: false,
  });
  slots.push({
    slot_id: "np2",
    row: 5,
    col: 2,
    cap_label: NUMPAD_ENTER_CAP,
    scancode: "",
    keycode: "enter",
    function_key_number: null,
    locked: false,
  });
  return slots;
}

export const isCalibrated = (slots = []) => slots.some((s) => s.scancode);

// showkey --scancodes prints hex with a 0x prefix (0x3b); evtest prints the bare
// HID value (70045). hwdb wants the bare hex either way, so prefixes are stripped
// and the digits lowercased as the technician types. Extended keys come out of
// showkey as a multi-byte sequence ("0xe0 0x4d") — the bytes are joined into the
// single hwdb code (e04d).
// An all-zero capture (0x00 0x00, or a longer run of them) means no scancode
// reached the console driver at all — it is discarded rather than written into the
// map, where a zero code would match no key and fail silently.
export const normalizeScancode = (v = "") => {
  const code = String(v).trim().split(/[\s,]+/).filter(Boolean)
    .map((b) => b.replace(/^0x/i, "").toLowerCase()).join("");
  return /^0+$/.test(code) ? "" : code;
};

// Which keycodes are already taken by another slot — prevents two physical keys
// firing the same POS action by accident.
export function duplicateKeycodes(slots = []) {
  const seen = {};
  slots.forEach((s) => {
    if (!s.keycode) return;
    seen[s.keycode] = (seen[s.keycode] || 0) + 1;
  });
  return Object.keys(seen).filter((k) => seen[k] > 1);
}

// The hwdb map baked into the read-only NFS image. This is the same file the PXE
// bootstrap emits — saving a layout here replaces the hardcoded fallback with the
// technician's captured map.
export function buildHwdbMap(layout) {
  const model = layout?.keyboard_model || DEFAULT_KEYBOARD_MODEL;
  const mapped = (layout?.slots || []).filter((s) => s.scancode && s.keycode);
  const lines = [
    `# /etc/udev/hwdb.d/70-sureflow-pos-keyboard.hwdb`,
    `# ${model} — generated by the visual key remapper`,
    `evdev:input:b0003v04B3p3025*`,
  ];
  if (!mapped.length) {
    lines.push(` # No scancodes captured yet — run the calibration steps first.`);
  }
  mapped.forEach((s) => {
    lines.push(` KEYBOARD_KEY_${s.scancode}=${s.keycode}   # ${s.cap_label}`);
  });
  lines.push(
    `# The override strip stays Ctrl so Ctrl+Action Code (F10) keeps firing the`,
    `# silent robbery alarm. Never reassign F9 or F10.`,
    ` KEYBOARD_KEY_70029=leftctrl`,
    ``,
    `# apply inside the image with:`,
    `#   systemd-hwdb update && udevadm trigger`,
  );
  return lines.join("\n");
}

export const CALIBRATION_COMMANDS = [
  "# On a lane — press each function key in turn and note the scancode it reports\nsudo evtest",
  "# Apply the saved map after installing it into the image\nsudo systemd-hwdb update && sudo udevadm trigger",
];